import java.util.HashMap;
import java.util.Scanner;
import java.util.Map;

 public class Main {
    public static void main(String[] args) {
        Map<Integer , String> elementAd= new HashMap<>();
        elementAd.put(1, "Hidrojen (H)");
        elementAd.put(2, "Helyum (He)");
        elementAd.put(3, "Lityum (Li)");
        elementAd.put(4, "Berilyum (Be)");
        elementAd.put(5, "Bor (B)");
        elementAd.put(6, "Karbon (C)");
        elementAd.put(7, "Azot (N)");
        elementAd.put(8, "Oksijen (O)");
        elementAd.put(9, "Flor (F)");
        elementAd.put(10, "Neon (Ne)");
        elementAd.put(11, "Sodyum (Na)");
        elementAd.put(12, "Magnezyum (Mg)");
        elementAd.put(13, "Alüminyum (Al)");
        elementAd.put(14, "Silisyum (Si)");
        elementAd.put(15, "Fosfor (P)");
        elementAd.put(16, "Kükürt (S)");
        elementAd.put(17, "Klor (Cl)");
        elementAd.put(18, "Argon (Ar)");
        elementAd.put(19, "Potasyum (K)");
        elementAd.put(20, "Kalsiyum (Ca)");
        elementAd.put(21, "Skandiyum (Sc)");
        elementAd.put(22, "Titanyum (Ti)");
        elementAd.put(23, "Vanadyum (V)");
        elementAd.put(24, "Krom (Cr)");
        elementAd.put(25, "Mangan (Mn)");
        elementAd.put(26, "Demir (Fe)");
        elementAd.put(27, "Kobalt (Co)");
        elementAd.put(28, "Nikel (Ni)");
        elementAd.put(29, "Bakır (Cu)");
        elementAd.put(30, "Çinko (Zn)");
        elementAd.put(31, "Galyum (Ga)");
        elementAd.put(32, "Germanyum (Ge)");
        elementAd.put(33, "Arsenik (As)");
        elementAd.put(34, "Selenyum (Se)");
        elementAd.put(35, "Brom (Br)");
        elementAd.put(36, "Kripton (Kr)");
        elementAd.put(37, "Rubidyum (Rb)");
        elementAd.put(38, "Stronsiyum (Sr)");
        elementAd.put(39, "İtriyum (Y)");
        elementAd.put(40, "Zirkonyum (Zr)");
        elementAd.put(41, "Niyobyum (Nb)");
        elementAd.put(42, "Molibden (Mo)");
        elementAd.put(43, "Teknetyum (Tc)");
        elementAd.put(44, "Rutenyum (Ru)");
        elementAd.put(45, "Rodyum (Rh)");
        elementAd.put(46, "Paladyum (Pd)");
        elementAd.put(47, "Gümüş (Ag)");
        elementAd.put(48, "Kadmiyum (Cd)");
        elementAd.put(49, "İndiyum (In)");
        elementAd.put(50, "Kalay (Sn)");
        elementAd.put(51, "Antimon (Sb)");
        elementAd.put(52, "Tellür (Te)");
        elementAd.put(53, "İyot (I)");
        elementAd.put(54, "Ksenon (Xe)");
        elementAd.put(55, "Sezyum (Cs)");
        elementAd.put(56, "Baryum (Ba)");
        elementAd.put(57, "Lantan (La)");
        elementAd.put(58, "Seryum (Ce)");
        elementAd.put(59, "Praseodim (Pr)");
        elementAd.put(60, "Neodim (Nd)");
        elementAd.put(61, "Prometyum (Pm)");
        elementAd.put(62, "Samaryum (Sm)");
        elementAd.put(63, "Avropiyum (Eu)");
        elementAd.put(64, "Gadolinyum (Gd)");
        elementAd.put(65, "Terbiyum (Tb)");
        elementAd.put(66, "Disprozyum (Dy)");
        elementAd.put(67, "Holmiyum (Ho)");
        elementAd.put(68, "Erbiyum (Er)");
        elementAd.put(69, "Tulyum (Tm)");
        elementAd.put(70, "İterbiyum (Yb)");
        elementAd.put(71, "Lutesyum (Lu)");
        elementAd.put(72, "Hafniyum (Hf)");
        elementAd.put(73, "Tantal (Ta)");
        elementAd.put(74, "Tungsten (W)");
        elementAd.put(75, "Renyum (Re)");
        elementAd.put(76, "Osmiyum (Os)");
        elementAd.put(77, "İridyum (Ir)");
        elementAd.put(78, "Platin (Pt)");
        elementAd.put(79, "Altın (Au)");
        elementAd.put(80, "Cıva (Hg)");
        elementAd.put(81, "Talyum (Tl)");
        elementAd.put(82, "Kurşun (Pb)");
        elementAd.put(83, "Bizmut (Bi)");
        elementAd.put(84, "Polonyum (Po)");
        elementAd.put(85, "Astatin (At)");
        elementAd.put(86, "Radon (Rn)");
        elementAd.put(87, "Fransiyum (Fr)");
        elementAd.put(88, "Radyum (Ra)");
        elementAd.put(89, "Aktinyum (Ac)");
        elementAd.put(90, "Toryum (Th)");
        elementAd.put(91, "Protaktinyum (Pa)");
        elementAd.put(92, "Uranyum (U)");
        elementAd.put(93, "Neptünyum (Np)");
        elementAd.put(94, "Plütonyum (Pu)");
        elementAd.put(95, "Amerikyum (Am)");
        elementAd.put(96, "Küriyum (Cm)");
        elementAd.put(97, "Berkelyum (Bk)");
        elementAd.put(98, "Kaliforniyum (Cf)");
        elementAd.put(99, "Einsteinyum (Es)");
        elementAd.put(100, "Fermiyum (Fm)");
        elementAd.put(101, "Mendelevyum (Md)");
        elementAd.put(102, "Nobelyum (No)");
        elementAd.put(103, "Lawrensiyum (Lr)");
        elementAd.put(104, "Rutherfordiyum (Rf)");
        elementAd.put(105, "Dubniyum (Db)");
        elementAd.put(106, "Seaborgiyum (Sg)");
        elementAd.put(107, "Bohriyum (Bh)");
        elementAd.put(108, "Hassiyum (Hs)");
        elementAd.put(109, "Meitneriyum (Mt)");
        elementAd.put(110, "Darmstadtiyum (Ds)");
        elementAd.put(111, "Röntgeniyum (Rg)");
        elementAd.put(112, "Kopernikyum (Cn)");
        elementAd.put(113, "Nihonyum (Nh)");
        elementAd.put(114, "Flerovyum (Fl)");
        elementAd.put(115, "Moskovyum (Mc)");
        elementAd.put(116, "Livermoryum (Lv)");
        elementAd.put(117, "Tennessin (Ts)");
        elementAd.put(118, "Oganesson (Og)");
        Scanner scanner = new Scanner(System.in);
        System.out.print("118 Element Arasından bulmak istediğiniz elementin atom numarasını yazınız : ");
        int elementAtomNum = scanner.nextInt();
        if (elementAd.containsKey(elementAtomNum))
            System.out.println(elementAd.get(elementAtomNum));
        else System.out.println("Geçersiz değer girdiniz.Tekrar deneyiniz.");
        scanner.close();
    }
}